services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
      target: builder
    environment:
      - NODE_ENV=development
    network_mode: host
    volumes:
      - ./server/src:/app/src
    command: bun run src/index.ts

  ttp:
    build:
      context: .
      dockerfile: Dockerfile.ttp
      target: builder
    environment:
      - NODE_ENV=development
    network_mode: host
    volumes:
      - ./ttp/src:/app/src
    command: bun run src/index.ts

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
      target: builder
    environment:
      - NODE_ENV=development
      - VITE_SERVER_URL=http://localhost:3001
      - VITE_TTP_URL=http://localhost:3002
    network_mode: host
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
    command: bun run dev -- --host

